name: truthordare
description: Truth or Dare

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.5
  flutter_bloc: ^6.1.2
  meta: ^1.1.8
  equatable: ^1.1.1
  permission_handler: ^5.0.0+hotfix.5
  barcode_scan: ^3.0.1
  app_settings: ^4.0.0
  intl: ^0.16.1
  double_back_to_close_app: ^0.1.2
  font_awesome_flutter: ^8.7.0
  liquid_pull_to_refresh: ^2.0.0
  dio: ^3.0.10
  shared_preferences: ^0.5.6+3
  flutter_secure_storage: ^3.3.3
  countdown_flutter: ^0.1.2
  no_context_navigation: ^1.0.2
  sqflite: ^1.3.0


  connectivity_wrapper: ^1.0.4

  get_it: ^5.0.6
  shimmer: ^1.1.2
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.1
  google_sign_in: ^4.5.9
  localstorage: ^3.0.6+9
  firebase_storage: ^7.0.0
  image_picker: ^0.6.7+22
  image_cropper: ^1.3.1
  flutter_exif_rotation: ^0.3.2
  photo_view: ^0.10.3



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    # - assets/flares/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: product-sans
      fonts:
        - asset: assets/fonts/product-sans/Product-Sans-Regular.ttf

    - family: source-sans-pro
      fonts:
        - asset: assets/fonts/source-sans-pro/SourceSansPro-Regular.ttf

    - family: intro
      fonts:
        - asset: assets/fonts/intro/Intro.otf

    - family: roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf

    - family: lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
